### ISSUE TITLE
Cinnamon support

### ISSUE THREAD

**Issue by mikkorantalainen** [poelzi/ulatencyd#42]
I'm running Ubuntu 12.04 with Cinnamon and ulatencyd. I think that following should be added to default configuration:

```
# /etc/ulatencyd/simple.d/cinnamon.conf
# cinnamon user interface and file manager
cinnamon                      user.ui
nemo                          user.ui
```

**Comment by hir3npatel** [comment]
Quick question, what about things like cinnamon-session, dbus-launch, cinnamon-settings etc. Are these not also needed to keep a desktop session responsive?
